Repository scorelab/LabelLab, pull requests merged in 2020-05, with the labels that each got.

#426 Create UI for model management dashboard
  labellab-client/src/components/project/css/models.css
  labellab-client/src/components/project/index.js
  labellab-client/src/components/project/models.js
  labellab-client/src/components/project/sidebar.js
Labels: web

#409 Add show password feature to the login page
  labellab-client/src/components/login/css/login.css
  labellab-client/src/components/login/index.js
Labels: web

#412 Add check to submit image only if lightbox not open
  labellab-client/src/components/project/images.js
Labels: web

#376 feat: dark mode support for the flutter application
  labellab_mobile/lib/labellab_app.dart
Labels: android

#416 Fix green border
  labellab_mobile/android/app/src/main/res/values/styles.xml
Labels: android

#395 Edit profile page UI
  labellab-client/src/components/profile/css/edit.css
  labellab-client/src/components/profile/css/profile.css
  labellab-client/src/components/profile/edit.js
  labellab-client/src/components/profile/index.js
Labels: web

#430 [fix] Fixed typo error
  labellab-client/.env.example
  labellab-client/src/utils/FetchAPI.js
Labels: web

#258 Add Heroku button
  README.md
  app.json
  labellab-client/src/components/labeller/index.js
  labellab-client/src/components/project/images.js
  labellab-server/app.js
  labellab-server/config/dbURI.js
  labellab-server/controller/image/imageControls.js
  labellab-server/controller/user/userControls.js
  labellab-server/package-lock.json
  labellab-server/package.json
  package.json
  static.json
Labels: reviewed

#344 Added History(classification) Searching Feature
  labellab_mobile/lib/screen/history/history_item.dart
  labellab_mobile/lib/screen/history/history_screen.dart
  labellab_mobile/lib/screen/history/history_search_screen.dart
Labels: reviewed

#401 Added confidence field for classifications in the app and backend
  labellab-server/controller/classification/classificationControls.js
  labellab_mobile/lib/model/classification_label.dart
  labellab_mobile/lib/screen/classification/classification_screen.dart
Labels: android, backend
